---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: '{{ include "iot-simulator.fullname" . }}-centos'
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "7"
    from:
      kind: DockerImage
      name: docker.io/centos:7
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: '{{ include "iot-simulator.fullname" . }}-fedora'
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "29"
    from:
      kind: DockerImage
      name: docker.io/fedora:29
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: '{{ include "iot-simulator.fullname" . }}-base'
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: '{{ include "iot-simulator.fullname" . }}-parent'
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: '{{ include "iot-simulator.fullname" . }}-operator'
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
