---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus-{{ include "iot-simulator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-{{ include "iot-simulator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-{{ include "iot-simulator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-{{ include "iot-simulator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: prometheus-{{ include "iot-simulator.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: prometheus-{{ include "iot-simulator.fullname" . }}
  labels:
    app: {{ include "iot-simulator.name" . }}
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  channel: preview
  name: prometheus
  source: rh-operators
---
kind: Prometheus
apiVersion: monitoring.coreos.com/v1
metadata:
  name: prometheus-{{ include "iot-simulator.fullname" . }}
  labels:
    app: '{{ include "iot-simulator.fullname" . }}'
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceAccountName: prometheus-{{ include "iot-simulator.fullname" . }}
  serviceMonitorSelector:
    matchLabels:
      metrics: {{ include "iot-simulator.fullname" . }}
  resources:
    requests:
      memory: 400Mi
  securityContext: {}
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "iot-simulator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iot-simulator.name" . }}
    helm.sh/chart: {{ include "iot-simulator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    metrics: {{ include "iot-simulator.fullname" . }}
spec:
  selector:
    matchLabels:
      metrics: {{ include "iot-simulator.fullname" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1s
